import os

readme_content = """<h1 align="center">KARMA 📈</h1>

<p align="center">
  <strong>Knowledge-Aware Reinforced Multi-Agent Framework for Autonomous Financial Investment Decision-Making</strong>
</p>

<p align="center">
  KARMA elevates Retrieval-Augmented Generation (RAG) from a read-only retrieval mechanism into a <strong>read-write learning system</strong>. By injecting an Active Knowledge Base (AKB) into a 12-node Multi-Agent System (MAS), KARMA builds persistent institutional memory. It tracks market insights, past trade decisions, and outcome-derived lessons to continuously improve its financial reasoning.
</p>

---

## 🌟 Key Innovations

1. **Active Knowledge Base (AKB) Agent**: Operates across a powerful closed-loop lifecycle:
   - **Phase 1 (Pre-Query)**: Retrieves context to ground analysis.
   - **Phase 2 (Post-Learn)**: Stores decision trails, debate logs, and confidence metrics.
   - **Phase 3 (Outcome Reflection)**: Compares past decisions with actual $T+1$ returns to synthesize actionable lessons.
2. **Three-Store Multi-RAG**: Separates institutional memory into ChromaDB vector stores:
   - 📂 **Market Insights (MI)**: Ongoing market observations.
   - 📂 **Trade History (TH)**: Historical decisions + confidence tracking.
   - 📂 **Lessons Learned (LL)**: Post-trade principles validated by actual equity movements.
3. **Multi-Agent Debate Pipeline**: A 12-node LangGraph orchestration utilizing domain-specific analysts, aggressive bull/bear debaters, and cautious risk managers.
4. **Cross-Ticker Learning**: Lessons generated by analyzing one ticker (e.g., GOOGL momentum) are semantically retrieved and applied to structurally similar setups for other tickers (e.g., AMZN).

---

## ⚙️ Architecture & Workflow

### The 12-Node Multi-Agent Pipeline
KARMA delegates domain-specific research before synthesizing a final trade decision.

```mermaid
graph TD
    classDef action fill:#dff,stroke:#333,stroke-width:2px;
    classDef agent fill:#fdf,stroke:#333,stroke-width:2px;
    classDef decision fill:#ffd,stroke:#333,stroke-width:2px;

    A[🧠 1. KB Pre-Query]:::action
    B[📊 2. Fundamentals Analyst]:::agent
    C[📈 3. Market Analyst]:::agent
    D[📰 4. News Analyst]:::agent
    E[💬 5. Social Analyst]:::agent
    F[🐂 6. Bull Researcher]:::agent
    G[🐻 7. Bear Researcher]:::agent
    H[🔬 8. Research Manager]:::decision
    I[🛡️ 9. Risk Manager]:::decision
    J[💰 10. Trader Agent]:::decision
    K[📋 11. Explainability]:::action
    L[💾 12. KB Post-Learn]:::action

    A -->|Context & Lessons| B & C & D & E
    B & C & D & E --> F
    B & C & D & E --> G
    F & G -->|Opposing Theses| H
    H -->|Recommendation| I
    I -->|Position Sizing & Risk| J
    J -->|Output: BUY/HOLD/SELL| K
    K --> L
    L -.->|T+1 to T+30 Feedback Loop| A
```

### The Learning Lifecycle
```mermaid
flowchart LR
    SessionN[Session N: Trader Decision Issued] --> Wait[Wait T+1: Actual Return Realized]
    Wait --> Reflect[Outcome Reflection: Verify Decision]
    Reflect --> Store[Store Lesson in Vector DB]
    Store --> SessionNext[Session N+1: Retrieve Lesson]
    SessionNext -.->|Improves Future Context| SessionN
```

---

## 📊 Paper Highlights & Results

KARMA was rigorously evaluated on **AAPL, GOOGL, and AMZN** over a live 5-day intraday window. Results indicated massive improvements via the learning mechanism:

| Metric | Result | Insight |
| :--- | :--- | :--- |
| **Market Alignment** | 15/15 Decisions | 100% of decisions aligned with subsequent market movement. |
| **Active Trade Win Rate** | 2/2 Trades | Both active trades executed profitably (No Losses, \$0 Drawdown). |
| **Learning Trade ROI** | +4.89% | The KB-guided AMZN trade returned **5.9x more** than earlier trades. |
| **Avg. Confidence Growth** | +17.0% | Agent confidence steadily climbed from 0.51 to 0.67 as knowledge accrued. |
| **Net Portfolio Return** | +$114.26 (+1.14%) | Calculated on an initial $10,000 baseline across the 5 days. |

*(Disclaimer: Evaluated in a controlled window. Past performance modeling does not guarantee future market results.)*

---

## 🚀 Quick Start

### 1. Installation

```bash
# Initialize and activate a virtual environment
python -m venv venv
source venv/bin/activate

# Install dependencies
pip install -r requirements.txt
```

### 2. Configuration

Copy the example environment file and configure your API keys (LLM providers, data APIs, etc.):
```bash
cp .env.example .env
```
Main orchestration settings (such as model providers, quick vs. deep models, and fallback logic) are located in `src/karma/config.py`.

### 3. Run the CLI Pipeline

Execute the standard trading workflow directly from your terminal:
```bash
python main.py --portfolio heavy_tech
```

### 4. Interactive Web Apps

KARMA includes several Streamlit dashboards for real-time visualization of the agent pipeline and reasoning:
```bash
# Full interactive trading workflow with live agent reasoning
streamlit run apps/app_main.py

# Lightweight streamlined interface
streamlit run apps/app_essential.py

# Backtesting and Outcome Evaluation tools
streamlit run apps/app_master_eval.py
```

---

## 📁 Repository Layout

```text
karma/
├── main.py
├── apps/               # Streamlit web dashboards
├── data/               # Input samples & reference historical data
├── docs/               # Architecture documents and research artifacts
├── src/karma/          # Core Module 
│   ├── agents/         # 12-Node pipeline agents (Trader, Analysts, KB, Risk)
│   ├── data/           # Loaders, ingestions, and fallbacks
│   ├── evaluation/     # Testing and backtesting utilities
│   ├── graph/          # LangGraph state machines
│   ├── rag/            # ChromaDB managers, Embeddings, Explanations
│   └── utils/          # Utility functions and LLM factories
├── storage/
│   ├── cache/          # TLL-based cache for YFinance, RSS, Reddit 
│   ├── kb/             # Persistent ChromaDB vector stores (MI, TH, LL)
│   └── results/        # Realized P&L outcomes and reports
└── tests/              # Pytest battery
```

---

## 🧪 Testing

To run the local test battery, including Knowledge Base retrieval tests and Graph state validations:
```bash
pytest tests -q
```

---

## 🤝 Contributing

Contributions are welcome! If you're adapting this architecture, please refer to `docs/CONTRIBUTING.md`. 
KARMA is designed to be modular. You can seamlessly swap components via `config.py` whether using OpenAI, Anthropic, Gemini, or localized Ollama models.

## 🎓 Citation

If you utilize KARMA's architecture or agentic evaluation mechanisms in your research, please cite our paper:
> **KARMA: Knowledge-Aware Reinforced Multi-Agent Framework for Autonomous Financial Investment Decision-Making**  
> Lakshya Rathi, Priyank Mishra, Shaik Shasha Vali, Divyanshi Agarwal, Richa Golash  
> *Department of CSE, Bennett University, Greater Noida, India*  

"""

with open("README.md", "w") as f:
    f.write(readme_content)

print("Updated README.md successfully.")
